# Generated by Django 4.1 on 2022-08-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_catalog_options_catalog_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catalog'},
        ),
    ]
