# Generated by Django 4.1 on 2022-08-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oredred',
            new_name='date_ordered',
        ),
    ]
